#!/bin/sh

            #########################################################
            #                                                       #
            #                    AUR Update Bot                     #
            #                                                       #
            #   Version: 1.0 (09/06/2015)                           #
            #   Author: Ian Brunelli <ian@brunelli.me>              #
            #   URL: https://github.com/ianbrunelli/aur-updatebot   #
            #                                                       #
            #########################################################

aur_check_update() {
  echo "==> Checking for pkgver() function"
  grep -e "^[[:space:]]*pkgver[[:space:]]*([[:space:]]*)[[:space:]]*{" -i PKGBUILD \
  > /dev/null ||
  { echo "No pkgver() function found." 2>&2
    return 71; }

  echo "==> Getting sources"
  OLD_PKGVER=$( grep -m 1 pkgver PKGBUILD | cut -f 1 -d "=" --complement | tr -d \'\" )
  makepkg -do --skipchecksums > "$2/${1}_update.log" 2>&1
  NEW_PKGVER=$( grep -m 1 pkgver PKGBUILD | cut -f 1 -d "=" --complement | tr -d \'\" )

  if [ "$OLD_PKGVER" == "$NEW_PKGVER" ]; then
    echo "$1 is up-to-date ($NEW_PKGVER)."
    return 70
  else
    echo "$1 is out-of-date ($OLD_PKGVER -> $NEW_PKGVER)."
  fi
}

build_package() {
  echo "==> Building package"
  makepkg > "$2/${1}_makepkg.log" 2>&1

  if [ $? != 0 ]; then
    echo "Build failed. See \"$2/${1}_makepkg.log\" for details." 2>&2
    if [ "$ENABLE_NOTIFY" == true ]; then
      send_notification "critical" "Error updating $1" \
      "Build failed. See \"$2/${1}_makepkg.log\" for details."
    fi
    if [ "$EMAIL_REPORTS" == true ]; then
      send_email "$1" "$2/${1}_makepkg.log" "Build failed."
    fi
    return 2
  else
    echo "Successfully built."
  fi
}

check_namcap() {
  echo "==> Checking package with namcap"
  namcap "$1-$NEW_PKGVER-*.pkg.tar.xz" > "$2/${1}_namcap.log" 2>&1

  NAMCAP_ERR=$( grep -c "$1 E:" "$2/${1}_namcap.log" )
  NAMCAP_WAR=$( grep -c "$1 W:" "$2/${1}_namcap.log" )

  if [ ${NAMCAP_ERR} -gt 0 ]; then
    echo "Namcap returned ${NAMCAP_ERR} error(s) and ${NAMCAP_WAR} warning(s)." \
         "See \"$2/${1}_namcap.log\" for details." 2>&2
    if [ "$ENABLE_NOTIFY" == true ]; then
      send_notification "critical" "Error updating $1" \
      "Namcap returned ${NAMCAP_ERR} error(s) and ${NAMCAP_WAR} warning(s). See \"$2/${1}_namcap.log\" for details."
    fi
    if [ "$EMAIL_REPORTS" == true ]; then
      send_email "$1" "$2/${1}_namcap.log" "Namcap returned ${NAMCAP_ERR} error(s) and ${NAMCAP_WAR} warning(s)."
    fi
    return 1
  elif [ ${NAMCAP_WAR} -gt 0 ]; then
    echo "Namcap returned ${NAMCAP_WAR} warning(s). See \"$2/${1}_namcap.log\" for details."
    if [ "$ENABLE_NOTIFY" == true ]; then
      send_notification "normal" "Warning updating $1" \
      "Namcap returned ${NAMCAP_WAR} warning(s). See \"$2/${1}_namcap.log\" for details."
    fi
    if [ "$EMAIL_REPORTS" == true ]; then
      send_email "$1" "$2/${1}_namcap.log" "Namcap returned ${NAMCAP_WAR} warning(s)."
    fi
  fi
}

get_user_packages() {
  echo "==> Getting packages maintained by $1"

  USER_PKGS=$( curl -s "https://aur4.archlinux.org/rpc.php?type=msearch&arg=$1" |
               grep -Po '"Name":.*?[^\\],' |
               cut -f 4 -d \" )

  [ "$USER_PKGS" ] &&
  echo $( wc -w <<< "$USER_PKGS" ) "package(s) found:" $USER_PKGS ||
  echo "No package found." 2>&2
}

send_email() {
  echo "==> Sending email to $REPORT_EMAIL"
  hash mail 2> /dev/null &&
  { mail -a "$2" -s "The package $1 requires your attention" "$REPORT_EMAIL" <<< "$3" ||
    return 1; } ||
  echo "The command mail was not found." 2>&2
}

send_notification() {
  if [ "$1" == "critical" ]; then
    ICON="software-update-urgent-symbolic"
  elif [ "$1" == "normal" ]; then
    ICON="dialog-warning-symbolic"
  else
    ICON="software-update-available-symbolic"
  fi

  hash notify-send 2> /dev/null &&
  { notify-send --urgency="$1" --icon="$ICON" --app-name="$SCRIPT_NAME" "$2" "$3" ||
    return 1; } ||
  echo "The command notify-send was not found." 2>&2
}

update_aur() {
  echo "==> Pushing new version to AUR"

  { git add PKGBUILD .SRCINFO 2>&1 | tee "$2/${1}_git.log" &&
    git commit -m "Updated version ($OLD_PKGVER -> $NEW_PKGVER)." \
               --author="AUR Update Bot <$AUTHOR_EMAIL>" 2>& 1 | tee -a "$2/${1}_git.log" &&
    git push 2>&1 | tee -a "$2/${1}_git.log"
  } ||
  { echo "Pushing to AUR failed. See \"$2/${1}_git.log\" for details." 2>&2
    if [ "$ENABLE_NOTIFY" == true ]; then
      send_notification "critical" "Error updating $1" \
      "Pushing to AUR failed. See \"$2/${1}_git.log\" for details."
    fi
    if [ "$EMAIL_REPORTS" == true ]; then
      send_email "$1" "$2/${1}_git.log" "Pushing to AUR failed."
    fi
  }
}

usage_guide() {
  echo -e "Usage: $SCRIPT_NAME [ OPTIONS ] [ PKGNAMES ]\n" \
          "\nOptions:" \
          "\n  -d or --dir <path> \tSave files in <path> instead of /tmp." \
          "\n  --disable-push \tDoesn't attempt to push the updated files to AUR." \
          "\n  --email <email> \tSend reports to <email>." \
          "\n  -n or --notify \tUse libnotify to send desktop notifications." \
          "\n  -u or --user <user> \tCheck updates for all packages maintained by <user>." \
          "\n  --config <file> \tSource <file> for configuration." \
          "\n  -h or --help \t\tPrint this message.\n" \
          "\nConfiguration:" \
          "\n  The global configuration file can be found in /etc/aurupbotrc." \
          "\n  You can have an user specific file in ~/.config/aurupbotrc."
}

SCRIPT_NAME=$( basename "$0" )
AUTHOR_EMAIL=$( git config user.email )

EMAIL_REPORTS=false
ENABLE_NOTIFY=false
ENABLE_PUSH=true
SAVE_DIR="/tmp/$SCRIPT_NAME-$USER"

[ -f "/etc/aurupbotrc" ] &&
source "/etc/aurupbotrc"

[ -f "$HOME/.config/aurupbotrc" ] &&
source "$HOME/.config/aurupbotrc"

unset AUR_USERS PKGS

while [ $# -gt 0 ]; do
  if [ "$1" == "--config" ]; then
    [ "$2" ] &&
    { source "$( readlink -f "$2" )"
      shift 2; } ||
    { usage_guide
      exit 1; }
  elif [[ $1 =~ ^-(d|-dir)$ ]]; then
    shift
    SAVE_DIR=$( readlink -f "$1" )
    shift
  elif [ "$1" == "--email" ]; then
    [ "$2" ] &&
    { EMAIL_REPORTS=true
      REPORT_EMAIL="$2"
      shift 2; } ||
    { usage_guide
      exit 1; }
  elif [[ $1 =~ ^-(h|-help)$ ]]; then
    usage_guide
    exit 0
  elif [[ $1 =~ ^-(n|-notify)$ ]]; then
    ENABLE_NOTIFY=true
    shift
  elif [[ $1 =~ ^-(u|-user)$ ]]; then
    shift
    [ "$1" ] &&
    { AUR_USERS+=" $1"
      shift; }
  elif [ "$1" == "--disable-push" ]; then
    ENABLE_PUSH=false
    shift
  elif [[ $1 =~ ^- ]]; then
    echo "`basename $0`: unrecognized option '$1'" >&2
    usage_guide
    exit 1
  else
    PKGS+=" $1"
    shift
  fi
done

for AUR_USER in ${AUR_USERS}; do
  get_user_packages "$AUR_USER"
  PKGS+=" $USER_PKGS"
done

if [ $( wc -w <<< "$PKGS" ) -gt 0 ] &&
   [ "$SAVE_DIR" ]; then
  mkdir -p "${SAVE_DIR}" ||
  exit 2
  cd "${SAVE_DIR}"
elif [[ ! $AUR_USERS ]]; then
  usage_guide
fi

for PKG in ${PKGS}; do
  unset OLD_PKGVER NEW_PKGVER NAMCAP_ERR NAMCAP_WAR

  [ -e "$PKG" ] &&
  { rm -rf "$PKG" ||
    exit 3; }

  echo "==> Cloning the AUR repository for $PKG"
  git clone "ssh://aur@aur4.archlinux.org/$PKG.git" "$PKG" --quiet &&
  { cd "$PKG"
    aur_check_update "$PKG" "$SAVE_DIR" &&
    build_package "$PKG" "$SAVE_DIR" &&
    check_namcap "$PKG" "$SAVE_DIR" &&
    { mksrcinfo &&
      if [ "$ENABLE_PUSH" == true ]; then
        update_aur "$PKG" "$SAVE_DIR" &&
        if [ "$ENABLE_NOTIFY" == true ]; then
          send_notification "low" "Successfully updated $PKG" \
          "The package $PKG was successfully updated and uploaded to AUR ($OLD_PKGVER -> $NEW_PKGVER)."
        fi
      else
        echo -e "\nThe package was successfully updated in \"$SAVE_DIR/$PKG\" ($OLD_PKGVER -> $NEW_PKGVER)."
        if [ "$ENABLE_NOTIFY" == true ]; then
          send_notification "low" "Successfully updated $PKG" \
          "The package was updated in \"$SAVE_DIR/$PKG\" ($OLD_PKGVER -> $NEW_PKGVER)."
        fi
      fi
    }
  }
done

exit 0
